# Generated by Django 4.1 on 2023-03-03 06:05

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=30, verbose_name='產品編碼')),
                ('product_name', models.CharField(max_length=500, verbose_name='產品名稱')),
                ('price', models.PositiveSmallIntegerField(verbose_name='價格')),
                ('sale_price', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='特價價格')),
                ('inventory', models.PositiveSmallIntegerField(verbose_name='庫存')),
                ('class_name', models.CharField(max_length=50, verbose_name='類別名稱')),
                ('app_name', models.CharField(max_length=50, verbose_name='APP名稱')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('latest_update_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, verbose_name='使用者帳號')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='token')),
                ('is_auth', models.BooleanField(default=False, verbose_name='是否為會員')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='創建日期')),
                ('latest_activate_date', models.DateTimeField(auto_now=True, verbose_name='最後活躍時間')),
            ],
            options={
                'unique_together': {('username', 'token'), ('username', 'is_auth')},
            },
        ),
        migrations.CreateModel(
            name='CartModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(default=1, verbose_name='數量')),
                ('valid', models.BooleanField(default=True, verbose_name='是否有效')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='創建日期')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_related', related_query_name='product_query', to='cart_api.productmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_related', related_query_name='user_query', to='cart_api.usermodel')),
            ],
        ),
    ]
