# Generated by Django 4.1 on 2023-02-13 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productmodel',
            unique_together={('product_id', 'class_name', 'app_name')},
        ),
    ]
