# Generated by Django 4.1 on 2023-02-13 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart_api', '0002_alter_productmodel_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productmodel',
            unique_together=set(),
        ),
    ]
