# Generated by Django 4.1 on 2023-02-16 10:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cart_api', '0003_alter_productmodel_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='is_auth',
            field=models.BooleanField(default=False, verbose_name='是否為會員'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='product_id',
            field=models.CharField(max_length=30, verbose_name='產品編碼'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='創建日期'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='latest_activate_date',
            field=models.DateTimeField(auto_now=True, verbose_name='最後活躍時間'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='token'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='username',
            field=models.CharField(max_length=30, verbose_name='使用者帳號'),
        ),
        migrations.AlterUniqueTogether(
            name='productmodel',
            unique_together={('product_id', 'class_name', 'app_name')},
        ),
    ]
