# Generated by Django 4.1 on 2023-02-18 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart_api', '0005_alter_productmodel_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usermodel',
            unique_together={('username', 'token'), ('username', 'is_auth')},
        ),
    ]
