# Generated by Django 3.2.4 on 2021-07-05 09:13

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import plant_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('plant_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChildImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_image', models.ImageField(upload_to='path/')),
                ('imageA', models.ImageField(blank=True, null=True, upload_to=plant_app.models.path)),
                ('imageB', models.ImageField(blank=True, null=True, upload_to=plant_app.models.path)),
                ('imageC', models.ImageField(blank=True, null=True, upload_to=plant_app.models.path)),
                ('imageD', models.ImageField(blank=True, null=True, upload_to=plant_app.models.path)),
                ('imageE', models.ImageField(blank=True, null=True, upload_to=plant_app.models.path)),
                ('imageF', models.ImageField(blank=True, null=True, upload_to=plant_app.models.path)),
                ('imageG', models.ImageField(blank=True, null=True, upload_to=plant_app.models.path)),
            ],
        ),
        migrations.CreateModel(
            name='ChildPlantModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, unique=True)),
                ('description', models.CharField(max_length=500)),
                ('price', models.IntegerField()),
                ('inventory', models.IntegerField(default=1)),
                ('status', models.CharField(blank=True, choices=[('I', '有庫存'), ('O', '無庫存')], default='I', max_length=1)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CustomerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('customer', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('tel', models.IntegerField()),
                ('address', models.CharField(max_length=50)),
                ('qty', models.IntegerField()),
                ('deal_date', models.DateField(default=django.utils.timezone.now)),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plant_app.childimagemodel')),
            ],
        ),
        migrations.CreateModel(
            name='MomPlantModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mom', models.CharField(max_length=50, unique=True)),
                ('mom_image', models.ImageField(upload_to='gallery/mom/')),
            ],
        ),
        migrations.DeleteModel(
            name='PlantModel',
        ),
        migrations.AddField(
            model_name='childplantmodel',
            name='category',
            field=models.OneToOneField(help_text='須從母株模型資料庫新增', on_delete=django.db.models.deletion.CASCADE, to='plant_app.momplantmodel', to_field='mom'),
        ),
        migrations.AddField(
            model_name='childimagemodel',
            name='name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='plant_app.childplantmodel', to_field='name'),
        ),
    ]
