# Generated by Django 3.2.4 on 2021-07-05 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plant_app', '0002_auto_20210705_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childplantmodel',
            name='category',
            field=models.ForeignKey(help_text='須從母株模型資料庫新增', on_delete=django.db.models.deletion.CASCADE, to='plant_app.momplantmodel', to_field='mom'),
        ),
    ]
