# Generated by Django 3.2.4 on 2021-07-04 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant_app', '0002_customermodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='customermodel',
            name='qty',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plantmodel',
            name='inventory',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
    ]
